<template>
  
  <article ref="article-4356">
    <h1>Excepteur sint occaecat</h1>
    <article-read-time element="article-4356"></article-read-time>
    <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. </h2>
    <p>Vestibulum nunc tellus, laoreet imperdiet condimentum a, tempor vel lacus. Etiam auctor purus egestas tincidunt placerat. Ut feugiat dignissim dolor vitae finibus. Ut sollicitudin enim justo, id dignissim nisl volutpat a. Pellentesque mollis a mi in commodo. Morbi gravida, orci dignissim gravida ultrices, neque est pretium felis, ut gravida mauris leo at odio. Aliquam sollicitudin neque et erat tempor, at lobortis erat imperdiet. Suspendisse congue diam vel quam vestibulum bibendum. Etiam congue varius iaculis. Maecenas justo velit, lacinia ut accumsan suscipit, fringilla ac lorem.</p>
    <p>Sed ultricies sem vel dui efficitur mollis. Vestibulum volutpat tristique mollis. Aliquam nec dictum sapien, et congue enim. Nunc ultricies nibh congue, tincidunt sem a, finibus augue. Curabitur vitae accumsan nibh, vitae aliquam orci. Curabitur aliquet nunc ipsum, quis mollis mauris commodo at. Phasellus eu elementum ligula. Maecenas tincidunt fermentum sapien, eu luctus lectus ornare sed.</p>
    <p>Nam lectus tellus, aliquet quis cursus non, aliquam pellentesque quam. Duis sit amet est tincidunt, posuere ex vitae, dignissim lorem. Maecenas a efficitur nibh, rutrum venenatis nulla. Morbi ut felis gravida, tristique mi vitae, ornare sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia interdum lorem sit amet gravida. Morbi et dignissim nunc. Sed quis molestie sem. Donec eu consequat ante. Nunc gravida ligula ac risus pretium tempus.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. Praesent id nunc finibus, eleifend turpis eget, laoreet dui. Mauris aliquam venenatis lobortis. Ut luctus mi vel turpis faucibus suscipit. Cras a elit in lacus tincidunt maximus. Suspendisse rutrum tempus est, a eleifend sapien mattis nec. Mauris in ultrices mi. Donec malesuada nulla vel pulvinar consectetur.</p>
    <p>Vestibulum nunc tellus, laoreet imperdiet condimentum a, tempor vel lacus. Etiam auctor purus egestas tincidunt placerat. Ut feugiat dignissim dolor vitae finibus. Ut sollicitudin enim justo, id dignissim nisl volutpat a. Pellentesque mollis a mi in commodo. Morbi gravida, orci dignissim gravida ultrices, neque est pretium felis, ut gravida mauris leo at odio. Aliquam sollicitudin neque et erat tempor, at lobortis erat imperdiet. Suspendisse congue diam vel quam vestibulum bibendum. Etiam congue varius iaculis. Maecenas justo velit, lacinia ut accumsan suscipit, fringilla ac lorem.</p>
    <p>Sed ultricies sem vel dui efficitur mollis. Vestibulum volutpat tristique mollis. Aliquam nec dictum sapien, et congue enim. Nunc ultricies nibh congue, tincidunt sem a, finibus augue. Curabitur vitae accumsan nibh, vitae aliquam orci. Curabitur aliquet nunc ipsum, quis mollis mauris commodo at. Phasellus eu elementum ligula. Maecenas tincidunt fermentum sapien, eu luctus lectus ornare sed.</p>
    <p>Nam lectus tellus, aliquet quis cursus non, aliquam pellentesque quam. Duis sit amet est tincidunt, posuere ex vitae, dignissim lorem. Maecenas a efficitur nibh, rutrum venenatis nulla. Morbi ut felis gravida, tristique mi vitae, ornare sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia interdum lorem sit amet gravida. Morbi et dignissim nunc. Sed quis molestie sem. Donec eu consequat ante. Nunc gravida ligula ac risus pretium tempus.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
  </article>

  <article ref="article-2784">
    <h1>Aenean at nibh augue.</h1>
    <article-read-time element="article-2784"></article-read-time>
    <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. Praesent id nunc finibus, eleifend turpis eget, laoreet dui. </h2>
    <p>Vestibulum nunc tellus, laoreet imperdiet condimentum a, tempor vel lacus. Etiam auctor purus egestas tincidunt placerat. Ut feugiat dignissim dolor vitae finibus. Ut sollicitudin enim justo, id dignissim nisl volutpat a. Pellentesque mollis a mi in commodo. Morbi gravida, orci dignissim gravida ultrices, neque est pretium felis, ut gravida mauris leo at odio. Aliquam sollicitudin neque et erat tempor, at lobortis erat imperdiet. Suspendisse congue diam vel quam vestibulum bibendum. Etiam congue varius iaculis. Maecenas justo velit, lacinia ut accumsan suscipit, fringilla ac lorem.</p>
    <p>Sed ultricies sem vel dui efficitur mollis. Vestibulum volutpat tristique mollis. Aliquam nec dictum sapien, et congue enim. Nunc ultricies nibh congue, tincidunt sem a, finibus augue. Curabitur vitae accumsan nibh, vitae aliquam orci. Curabitur aliquet nunc ipsum, quis mollis mauris commodo at. Phasellus eu elementum ligula. Maecenas tincidunt fermentum sapien, eu luctus lectus ornare sed.</p>
    <p>Nam lectus tellus, aliquet quis cursus non, aliquam pellentesque quam. Duis sit amet est tincidunt, posuere ex vitae, dignissim lorem. Maecenas a efficitur nibh, rutrum venenatis nulla. Morbi ut felis gravida, tristique mi vitae, ornare sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia interdum lorem sit amet gravida. Morbi et dignissim nunc. Sed quis molestie sem. Donec eu consequat ante. Nunc gravida ligula ac risus pretium tempus.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. Praesent id nunc finibus, eleifend turpis eget, laoreet dui. Mauris aliquam venenatis lobortis. Ut luctus mi vel turpis faucibus suscipit. Cras a elit in lacus tincidunt maximus. Suspendisse rutrum tempus est, a eleifend sapien mattis nec. Mauris in ultrices mi. Donec malesuada nulla vel pulvinar consectetur.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    <p>Vestibulum nunc tellus, laoreet imperdiet condimentum a, tempor vel lacus. Etiam auctor purus egestas tincidunt placerat. Ut feugiat dignissim dolor vitae finibus. Ut sollicitudin enim justo, id dignissim nisl volutpat a. Pellentesque mollis a mi in commodo. Morbi gravida, orci dignissim gravida ultrices, neque est pretium felis, ut gravida mauris leo at odio. Aliquam sollicitudin neque et erat tempor, at lobortis erat imperdiet. Suspendisse congue diam vel quam vestibulum bibendum. Etiam congue varius iaculis. Maecenas justo velit, lacinia ut accumsan suscipit, fringilla ac lorem.</p>
    <p>Sed ultricies sem vel dui efficitur mollis. Vestibulum volutpat tristique mollis. Aliquam nec dictum sapien, et congue enim. Nunc ultricies nibh congue, tincidunt sem a, finibus augue. Curabitur vitae accumsan nibh, vitae aliquam orci. Curabitur aliquet nunc ipsum, quis mollis mauris commodo at. Phasellus eu elementum ligula. Maecenas tincidunt fermentum sapien, eu luctus lectus ornare sed.</p>
    <p>Nam lectus tellus, aliquet quis cursus non, aliquam pellentesque quam. Duis sit amet est tincidunt, posuere ex vitae, dignissim lorem. Maecenas a efficitur nibh, rutrum venenatis nulla. Morbi ut felis gravida, tristique mi vitae, ornare sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia interdum lorem sit amet gravida. Morbi et dignissim nunc. Sed quis molestie sem. Donec eu consequat ante. Nunc gravida ligula ac risus pretium tempus.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. Praesent id nunc finibus, eleifend turpis eget, laoreet dui. Mauris aliquam venenatis lobortis. Ut luctus mi vel turpis faucibus suscipit. Cras a elit in lacus tincidunt maximus. Suspendisse rutrum tempus est, a eleifend sapien mattis nec. Mauris in ultrices mi. Donec malesuada nulla vel pulvinar consectetur.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nibh augue. Proin suscipit velit neque, et sodales enim blandit vel. Praesent id nunc finibus, eleifend turpis eget, laoreet dui. Mauris aliquam venenatis lobortis. Ut luctus mi vel turpis faucibus suscipit. Cras a elit in lacus tincidunt maximus. Suspendisse rutrum tempus est, a eleifend sapien mattis nec. Mauris in ultrices mi. Donec malesuada nulla vel pulvinar consectetur.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    <p>Vestibulum nunc tellus, laoreet imperdiet condimentum a, tempor vel lacus. Etiam auctor purus egestas tincidunt placerat. Ut feugiat dignissim dolor vitae finibus. Ut sollicitudin enim justo, id dignissim nisl volutpat a. Pellentesque mollis a mi in commodo. Morbi gravida, orci dignissim gravida ultrices, neque est pretium felis, ut gravida mauris leo at odio. Aliquam sollicitudin neque et erat tempor, at lobortis erat imperdiet. Suspendisse congue diam vel quam vestibulum bibendum. Etiam congue varius iaculis. Maecenas justo velit, lacinia ut accumsan suscipit, fringilla ac lorem.</p>
    <p>Sed ultricies sem vel dui efficitur mollis. Vestibulum volutpat tristique mollis. Aliquam nec dictum sapien, et congue enim. Nunc ultricies nibh congue, tincidunt sem a, finibus augue. Curabitur vitae accumsan nibh, vitae aliquam orci. Curabitur aliquet nunc ipsum, quis mollis mauris commodo at. Phasellus eu elementum ligula. Maecenas tincidunt fermentum sapien, eu luctus lectus ornare sed.</p>
    <p>Nam lectus tellus, aliquet quis cursus non, aliquam pellentesque quam. Duis sit amet est tincidunt, posuere ex vitae, dignissim lorem. Maecenas a efficitur nibh, rutrum venenatis nulla. Morbi ut felis gravida, tristique mi vitae, ornare sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia interdum lorem sit amet gravida. Morbi et dignissim nunc. Sed quis molestie sem. Donec eu consequat ante. Nunc gravida ligula ac risus pretium tempus.</p>
    <p>Ut iaculis vulputate nisi, eu porta velit imperdiet nec. Nunc a feugiat erat. Sed venenatis consequat turpis quis semper. Sed vitae justo sed nibh pulvinar pretium. Phasellus efficitur eleifend pretium. Mauris in auctor felis, a iaculis odio. Sed libero purus, dapibus vitae ornare vel, bibendum sit amet magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas lacus diam, semper eget placerat sit amet, faucibus eu neque. Suspendisse suscipit non nisl nec feugiat. Donec lacus justo, gravida sit amet magna eget, posuere vulputate mauris. Sed rhoncus lacus pretium elit porttitor, nec ullamcorper odio laoreet.</p>
    
  </article>
  


  <div class="copyright">
    <a href="https://github.com/BoraKucukkara/" title="Bora Kucukkara /  on Github">
      <svg height="24" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="24" data-view-component="true" class="octicon octicon-mark-github v-align-middle">
        <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
      </svg>
    </a>
    <a href="https://www.borakucukkara.com/" title="Bora Kucukkara personal web site">
      <img src="https://www.borakucukkara.com/borakucukkara.png" width="24">
    </a>
  </div>
</template>

<script>
import articleReadTime from './components/article-read-time.vue';
export default {
  components: {
    articleReadTime
  }
}
</script>
<style>
</style>
